import { chromium } from "playwright";
import path from "path";
import { fileURLToPath } from "url";
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage();
page.on("pageerror", err => console.log("ERROR:", err.message));
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto("http://localhost:5173", { waitUntil: "networkidle", timeout: 30000 });
await page.waitForTimeout(3000);
const spath = path.join(__dirname, "hero_check.png");
await page.screenshot({ path: spath, fullPage: false });
console.log("Saved:", spath);
await page.evaluate(() => window.scrollTo(0, 1800));
await page.waitForTimeout(1000);
const spath2 = path.join(__dirname, "sections_check.png");
await page.screenshot({ path: spath2, fullPage: false });
console.log("Saved sections:", spath2);
await browser.close();
